# Projects
[[projects]]
title = "Watermark+1"
link = "https://owlzou.github.io/watermark1"
cover = ""
description="åœ¨çº¿ç»™å›¾ç‰‡æ·»åŠ æ°´å°ã€‚"

[[projects]]
title = "ğŸ“” Text Tool"
link = "https://owlzou.github.io/text-tool/"
cover = ""
description="æ–‡å­—å¤„ç†å·¥å…·ï¼ˆæ­£åˆ™ã€ç¼–ç ã€jsç›´æ¥å¤„ç†ç­‰ï¼‰"

[[projects]]
title = "Z Shader Viewer"
link = "https://owlzou.github.io/zsv/"
cover = ""
description="ç€è‰²å™¨ç¼–è¾‘å™¨ï¼ˆå¤§æ¦‚ï¼‰"